# Generated by Django 5.0 on 2023-12-27 09:18

import django.core.validators
import my_plants_CBV.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('outdoor', 'Outdoor Plants'), ('indoor ', 'Indoor  Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), my_plants_CBV.web.validators.validate_string_is_only_letters])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plants_CBV.web.validators.validate_string_start_with_capital])),
                ('last_name', models.CharField(max_length=20, validators=[my_plants_CBV.web.validators.validate_string_start_with_capital])),
            ],
        ),
    ]
